### ISSUE TITLE
Where are the specs?

### ISSUE THREAD

**Issue by binki** [3nsoft/3nweb-protocols#1]
I looked in the README but couldn’t find an obvious reference to the specs that are being described. Where are they? Or is the demo implementation itself to be the spec?

**Comment by 3n-mb** [comment]
Do run it. Follow console instructions. Check browser console, as well.
The whole code is a demo implementation.

**Comment by 3n-mb** [comment]
Interactive demo is better than a dry _text_ spec. Its more fun to poke actual running system. And it shows key concepts.

As for the dry spec, it has to be a test-suite altogether. And it is coming with an _actual_ server implementation. It will be a separate project, while this one is going to stay for graphics, docs, etc.

**Comment by 3n-mb** [comment]
@binki if you are after MailerId implementation, in relation to your work with [portier](https://github.com/portier/portier.github.io/issues/13), I can put server code now. MailerId part of it has already been completed.
Let me know.
